name: Rustic Rat
favicon: null
layout_spectrum: 0.9994
typography_spectrum: 0.41732514882460237
title: RUSTIC RAT  Repurposing Everything
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#f50a09'
    - '#f7b340'
    - '#6f6f6f'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.22984264162369072
purpose: []
